"""
Application configuration
"""
DEBUG = True
DEBUG_LOG_FILE_PATH = ''
# NON DEBUG LOGS / ERROR LOGS ARE LOGGED IN SYSLOG

AWS_IOT_ROOT_CA_PATHi = ''
AWS_IOT_PRIVATE_KEY_PATH = ''
AWS_IOT_CLIENT_CA_PATH = ''

ZWAVE_PROXY_THREADS = 2

